version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_DATABASE=blog
            - DB_USERNAME=blog
            - DB_PASSWORD=blog_password

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=blog
            - MYSQL_USER=blog
            - MYSQL_PASSWORD=blog_password
            - MYSQL_ROOT_PASSWORD=root_password
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
